# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new debug build to the pgyer"
  lane :debug do|option|
    build_app(export_method: "ad-hoc", configuration: "Debug", scheme: "Poetry", silent: true, clean: true, output_directory: "~/Documents/Apps/Beta_#{Time.now.strftime('%Y-%m-%d_%H-%M-%S')}", output_name: "Poetry.ipa")
    pgyer(api_key: "cf2cf2bd3acead35dce53edc894e1ce9", user_key: "99b69b65cfc05866adcf21ea933ff87f", update_description: "#{option[:desc]}\n测试环境")
  end
  
  desc "Push a new release build to the pgyer"
  lane :release do|option|
    build_app(export_method: "ad-hoc", scheme: "Poetry", silent: true, clean: true, output_directory: "~/Documents/Apps/Release_#{Time.now.strftime('%Y-%m-%d_%H-%M-%S')}", output_name: "Poetry.ipa")
    pgyer(api_key: "cf2cf2bd3acead35dce53edc894e1ce9", user_key: "99b69b65cfc05866adcf21ea933ff87f", update_description: "#{option[:desc]}\n正式环境")
  end

  desc "Push a new build to the TestFlight"
  lane :testflight do
    build_app(export_method: "app-store", scheme: "Poetry", silent: true, clean: true, output_directory: "~/Documents/Apps/TestFlight_#{Time.now.strftime('%Y-%m-%d_%H-%M-%S')}", output_name: "Poetry.ipa")
    upload_to_testflight
  end

  desc "Push a new build to the AppStore"
  lane :appstore do
    #increment_build_number
    build_app(export_method: "app-store", scheme: "Poetry", clean: true, output_directory: "~/Documents/Apps/AppStore_#{Time.now.strftime('%Y-%m-%d_%H-%M-%S')}", output_name: "Poetry.ipa")
    upload_to_app_store
  end
end
